import 'package:flutter/material.dart';

final Map<String, Map<String, Map<String, int>>> itemMacronutrients = {
  'Chicken (Adobong Iga)': {
    'laman': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
    'Pitso/Breast': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
    'Binti': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
    'Hita': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
    'Pakpak': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
  },
  'Chicken (Chicken Inasal)': {
    'laman': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
    'Pitso/Breast': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
    'Binti': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
    'Hita': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
    'Pakpak': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
  },
  'Chicken (Fried Chicken)': {
    'laman': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'warnings': 2,
      'meal': 2,
    },
    'Pitso/Breast': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'warnings': 2,
      'meal': 2,
    },
    'Binti': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 2,
      'meal': 2,
    },
    'Hita': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 2,
      'meal': 2,
    },
    'Pakpak': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 2,
      'meal': 2,
    },
  },
  'Fish (Pan Fried Tilapia)': {
    'Head': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
    'Body': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
    'Tail': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
  },
  'Fish (Sinaing na Tulingan)': {
    'Head': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
    'Body': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
    'Tail': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 0,
      'meal': 2,
    },
  },
  'Pork (Breaded Pork Chop)': {
    'Slice': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'warnings': 4,
      'meal': 2,
    },
  },
  'Pork (Lechon Kawali)': {
    'Leg': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 4,
      'meal': 2,
    },
    'Wing': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 4,
      'meal': 2,
    },
    'Breast': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 4,
      'meal': 2,
    },
    'Thigh': {
      'fats': 5,
      'carbs': 5,
      'proteins': 5,
      'warnings': 4,
      'meal': 2,
    },
  },
  'Pork (Pork Bistek)': {
    'Slice': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 2,
    },
  },
  'Scrambled Egg': {
    'Chiken Egg': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 3,
    },
  },
  'Sunny Side Up Egg': {
    'Chiken Egg': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'warnings': 0,
      'meal': 3,
    },
  },
  'White Rice (Fried Rice)': {
    'Whole Cup': {
      'fats': 0,
      'carbs': 46,
      'proteins': 4,
      'warnings': 0,
      'meal': 1,
    },
    'Half Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'warnings': 0,
      'meal': 1,
    },
  },
  'White Rice (Boiled Rice)': {
    'Whole Cup': {
      'fats': 0,
      'carbs': 46,
      'proteins': 4,
      'warnings': 0,
      'meal': 3,
    },
    'Half Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'warnings': 0,
      'meal': 3,
    },
  },
  'Bread': {
    'Pandesal': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'warnings': 0,
      'meal': 1,
    },
    'Ensaymada': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'warnings': 3,
      'meal': 1,
    },
  },
};
