// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFzD4z4enU6gy25n4rsyLQsSkK_hIgdo',
    appId: '1:211469976440:web:1aa68653a1375345c83e8d',
    messagingSenderId: '211469976440',
    projectId: 'healthlens-fd034',
    authDomain: 'healthlens-fd034.firebaseapp.com',
    storageBucket: 'healthlens-fd034.appspot.com',
    measurementId: 'G-SQDF6K8QY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4nRJsmNA3wb2ARtco-Dg_9Jls5coXLy4',
    appId: '1:211469976440:android:1a283faffade1393c83e8d',
    messagingSenderId: '211469976440',
    projectId: 'healthlens-fd034',
    storageBucket: 'healthlens-fd034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimGikip5XZbUDnG_duwFn4pvzx_G9P_8',
    appId: '1:211469976440:ios:4882fb216614dd43c83e8d',
    messagingSenderId: '211469976440',
    projectId: 'healthlens-fd034',
    storageBucket: 'healthlens-fd034.appspot.com',
    iosBundleId: 'com.example.healthlens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimGikip5XZbUDnG_duwFn4pvzx_G9P_8',
    appId: '1:211469976440:ios:4882fb216614dd43c83e8d',
    messagingSenderId: '211469976440',
    projectId: 'healthlens-fd034',
    storageBucket: 'healthlens-fd034.appspot.com',
    iosBundleId: 'com.example.healthlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNFzD4z4enU6gy25n4rsyLQsSkK_hIgdo',
    appId: '1:211469976440:web:9175c9bd70c73d00c83e8d',
    messagingSenderId: '211469976440',
    projectId: 'healthlens-fd034',
    authDomain: 'healthlens-fd034.firebaseapp.com',
    storageBucket: 'healthlens-fd034.appspot.com',
    measurementId: 'G-Y61LFR0DKV',
  );
}
